from sqlalchemy.orm import Session
from datetime import datetime
from app.models import MercedesManual , ManualChunk

def create_manual_record(db: Session, manual_data: dict):
    # 1. Check if the hash already exists to avoid duplicates
    existing = db.query(MercedesManual).filter(
        MercedesManual.content_hash == manual_data['content_hash']
    ).first()
    
    if existing:
        print(f"Manual already exists with ID: {existing.id}")
        return existing

    # 2. Create the new object
    new_manual = MercedesManual(
        chassis_code=manual_data['chassis_code'],
        year=manual_data['year'],
        model=manual_data.get('model'),
        language=manual_data.get('language', 'en'),
        file_name=manual_data.get('file_name'),
        content_hash=manual_data['content_hash'],
        title=manual_data.get('title'),
        slug=manual_data.get('slug'),
        description=manual_data.get('description', ''),
        source_url=manual_data.get('source_url'),
        # Set timestamps manually since the column is String(50)
        created_at=datetime.now().isoformat(),
        updated_at=datetime.now().isoformat()
    )

    # 3. Add to session and save
    try:
        db.add(new_manual)
        db.commit()
        db.refresh(new_manual) # This gets the 'id' generated by Postgres
        return new_manual
    except Exception as e:
        db.rollback() # Undo changes if something goes wrong
        print(f"Error creating manual: {e}")
        raise e
    
def create_chunks_records(db: Session, chunks: list, manual_id: int):
    """
    Saves the processed chunks into the PostgreSQL database using SQLAlchemy.
    This function should be called after processing the PDF and generating chunks.
    """
    from app.ai_models import get_embedding_model
    
    embedding_model = get_embedding_model()
    
    for chunk in chunks:
        # Compute embedding for the chunk
        embedding_vector = embedding_model.embed_query(chunk.page_content)
        
        new_chunk = ManualChunk(
            manual_id=manual_id,
            content=chunk.page_content,
            metadata_info=chunk.metadata,
            embedding=embedding_vector
        )
        db.add(new_chunk)
    
    try:
        db.commit()
        print(f"Successfully saved {len(chunks)} chunks to database.")
    except Exception as e:
        db.rollback()
        print(f"Error saving chunks: {e}")
        raise